[project]
name = "perceptron-to-transformer"
version = "0.0.1"
description = "Go from creating a single perceptron all the way to modern transformers, all from scratch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
